// Real save, live/offline pickup and confirmation paths: destructive filters must agree.
const assert=require('node:assert/strict');
const {createGame}=require('./helpers/game');const g=createGame(),ev=g.ev;
let pass=0;
function test(name,code){ev(`S=fresh();S.eq={};S.auto=false;S.autoSell=Array(7).fill(true);S.autoSellRules=defaultAutoSellRules();autoSellDraft=null;autoSellPreview=null;`);assert.equal(ev(`(()=>{${code}})()`),true,name);console.log('ok '+name);pass++;}
ev(`window.testGear=(id,extra={})=>({id,name:'Test Sword',slot:'weapon',wt:'sword',tier:2,sec:1,lvl:20,val:20,aff:[],cards:[],slots:0,...extra});`);
test('rarity plus slot plus family plus exact name all constrain sales',`const i=testGear(1);S.autoSellRules.slots=['weapon'];S.autoSellRules.weapons=['bow'];if(autoSellMatches(i))return false;S.autoSellRules.weapons=['sword'];S.autoSellRules.names=['Different'];if(autoSellMatches(i))return false;S.autoSellRules.names=[i.name];if(!autoSellMatches(i))return false;S.autoSell[2]=false;return !autoSellMatches(i);`);
test('any/all affix keep modes and minimum thresholds',`const i=testGear(1,{aff:[{k:'crit',v:3},{k:'str',v:6}]});S.autoSellRules.affixes=[{k:'crit',min:3},{k:'cdm',min:8}];if(autoSellMatches(i))return false;S.autoSellRules.mode='all';if(!autoSellMatches(i))return false;i.aff.push({k:'cdm',v:8});if(autoSellMatches(i))return false;S.autoSellRules.affixes=[{k:'crit',min:4}];return autoSellMatches(i);`);
test('empty keep rules never keep every item accidentally',`S.autoSellRules.mode='all';return autoSellMatches(testGear(1));`);
test('locked, equipped, saved-loadout and reforge items are always kept',`const a=testGear(1,{locked:true}),b=testGear(2),c=testGear(3),d=testGear(4);S.eq.weapon=b;S.base.Knight={eq:{weapon:c.id}};S.reforgePending={id:d.id};return [a,b,c,d].every(i=>!autoSellMatches(i));`);
test('refinement, cards and empty-slot protections work independently',`const a=testGear(1,{r:1}),b=testGear(2,{cards:[{id:3}]}),c=testGear(4,{slots:3});S.autoSellRules.minEmpty=2;if([a,b,c].some(autoSellMatches))return false;S.autoSellRules.refined=false;S.autoSellRules.socketed=false;S.autoSellRules.minEmpty=0;return [a,b,c].every(autoSellMatches);`);
test('live and offline drops share affix protection and full-bag behavior',`S.autoSellRules.affixes=[{k:'crit',min:3}];const before=S.zeny;collect(testGear(1));const live=S.zeny-before;const r={items:0,drops:0,zeny:0,autoSold:0,overflow:0,storedItems:0};offlineStoreGear(testGear(2),r);if(r.autoSold!==1||r.zeny!==live)return false;collect(testGear(3,{aff:[{k:'crit',v:3}]}));offlineStoreGear(testGear(4,{aff:[{k:'crit',v:3}]}),r);if(S.inv.length!==2)return false;S.inv=Array.from({length:BAGMAX},(_,i)=>testGear(100+i));const z=S.zeny;collect(testGear(5001));offlineStoreGear(testGear(5002),r);return S.inv.length===BAGMAX&&S.zeny-z===2*live;`);
test('preview cannot pay out and confirmation rechecks protection plus item existence',`const a=testGear(1),b=testGear(2),c=testGear(3),d=testGear(4);S.inv=[a,b,c,d];const z=S.zeny;ACT.sellnow();if(S.inv.length!==4||S.zeny!==z)return false;a.locked=true;S.base.Knight={eq:{weapon:b.id}};S.inv.splice(S.inv.indexOf(c),1);S.inv.push(testGear(5));ACT.sellconfirm();const paid=S.zeny;ACT.sellconfirm();return S.inv.length===3&&S.inv.some(x=>x.id===5)&&S.zeny===paid&&paid-z===sellVal(d);`);
test('changing active rarity after preview keeps affected items',`S.inv=[testGear(1)];ACT.sellnow();S.autoSell[2]=false;ACT.sellconfirm();return S.inv.length===1&&S.zeny===0;`);
test('socketed cards returned when protection explicitly disabled',`S.autoSellRules.socketed=false;S.inv=[testGear(1,{cards:[{id:44,n:'Poring Card',v:1}]} )];ACT.sellnow();ACT.sellconfirm();return S.inv.length===0&&S.cards.some(c=>c.id===44);`);
test('draft presets do not affect drops until saved and account switches discard drafts',`ACT.sellpreset('caster');if(S.autoSellRules.affixes.length)return false;ACT.sellrulesapply();if(!S.autoSellRules.affixes.some(x=>x.k==='matk'))return false;ACT.sellpreset('physical');S=fresh();return sellDraft().affixes.length===0;`);
test('save/load preserves valid rules and legacy rarity flags',`S.autoSellRules={...defaultAutoSellRules(),slots:['weapon'],weapons:['dagger'],names:['Test Dagger'],affixes:[{k:'crit',min:3.5}],minEmpty:2};const rules=JSON.stringify(S.autoSellRules);localStorage.setItem(saveKey(),JSON.stringify(S));const loaded=load();return JSON.stringify(loaded.autoSellRules)===rules&&loaded.autoSell.every(Boolean);`);
test('malformed filters fail closed on load without selling inventory',`for(const broken of [null,[],{version:1}, {...defaultAutoSellRules(),affixes:[{k:'crit',min:-1}]},{...defaultAutoSellRules(),slots:['unknown']},{...defaultAutoSellRules(),names:[''] }]){S=fresh();S.autoSell=Array(7).fill(true);S.autoSellRules=broken;S.inv=[testGear(1)];if(autoSellMatches(S.inv[0]))return false;localStorage.setItem(saveKey(),JSON.stringify(S));const out=load();if(out.autoSell.some(Boolean)||out.inv.length!==1)return false;}return true;`);
test('old saves keep flags and receive protective defaults',`delete S.autoSellRules;localStorage.setItem(saveKey(),JSON.stringify(S));const out=load();return out.autoSell.every(Boolean)&&out.autoSellRules.refined&&out.autoSellRules.socketed;`);
g.close();console.log(pass+' auto-sell checks passed');
