// Generate the GM picker from the actual game, never a second handwritten item database.
// Run after changing drop tables: node tools/build_gm_catalog.cjs
const fs=require('node:fs'),{createGame}=require('./tests/helpers/game');
const game=createGame();
try {
 const data=game.ev(`JSON.stringify((()=>{
  const oldRandom=Math.random;Math.random=()=>.5;
  try{
   const entries=[],seen=new Set();
   for(let m=0;m<MAPS.length;m++)for(let stage=1;stage<=15;stage++){
    S.mp=m;S.lvl=stage;
    for(const T of gearPool(m,stage)){
     const key=m+':'+T.sec+':'+T.tier+':'+T.k+':'+T.n+':'+T.quality;
     if(seen.has(key))continue;seen.add(key);
     const item=genGear(T,fieldPower(m,stage),T.sec,false,T.tier);delete item.id;
     entries.push({id:'gear:'+key,label:item.name+' · '+MAPS[m].n+' · '+T.k,type:'gear',item,affixes:affixPool(item)});
    }
   }
   for(const c of CARD_CATALOG){const item=newCard(c);delete item.id;entries.push({id:'card:'+c.cardKey,label:item.n,type:'card',item});}
   for(const [resource,label] of [['ori','Oridecon'],['elu','Elunium'],['shards','Echo Shards'],['dps','Drop Protection Scroll'],['refineScrolls','Refine Scroll (placeholder)'],...NM_MAT.map((n,i)=>['nm'+i,n])])entries.push({id:resource,resource,label,type:'resource'});
   return {entries,affixes:AL,skills:Object.fromEntries(SKILLS.map(x=>[x.id,x.n])),sections:SECN,rarities:RAR.map(x=>x.n),slotStats:Object.fromEntries(Object.entries(SLOTS).map(([k,v])=>[k,v.stat])),slots:EQK.map(([id,label])=>({id,label})),classes:Object.fromEntries(Object.entries(CLASSES).map(([k,c])=>[k,{tier:c.tier,wt:c.wt}]))};
  }finally{Math.random=oldRandom}
 })())`);
 const output='// Generated by tools/build_gm_catalog.cjs from index.html. Do not hand edit.\nexport const GM_CATALOG = '+JSON.stringify(JSON.parse(data)).replace(/},\{"id":/g,'},\n{"id":')+';\n';
 const file=__dirname+'/../functions/_lib/gm-catalog.js';
 if(process.argv.includes('--check')){if(fs.readFileSync(file,'utf8')!==output)throw Error('GM catalog is stale');console.log('GM catalog is current');}
 else{fs.writeFileSync(file,output);console.log('Wrote GM catalog');}
}finally{game.close()}
