#!/usr/bin/env python3
"""Build every sprite atlas: PNG into assets/ + one JS file of data URIs.

usage: python3 build_atlas.py
"""
from PIL import Image
import base64, json, os
import spr_core as C
import spr_human as H
import spr_anime as A
import spr_thief as T
import spr_mob as M

ASSETS = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'assets')


def rows():
    """-> [(row, kind, frame)] for the 10-row layout."""
    out = []
    for k, n in ((0, C.IDLE), (1, C.WALK), (2, C.ATK)):
        for f in range(n):
            out.append((len(out), k, f))
    return out


ROWS = rows()


def build(draw):
    """draw(dir, kind, frame) -> 64x96 cell."""
    im = Image.new('RGBA', (C.CELL_W * C.DIRS, C.CELL_H * len(ROWS)), (0, 0, 0, 0))
    for d in range(C.DIRS):
        for row, kind, fr in ROWS:
            im.alpha_composite(draw(d, kind, fr), (d * C.CELL_W, row * C.CELL_H))
    return im


def data_uri(im):
    import io
    buf = io.BytesIO()
    im.save(buf, format='PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')


def main():
    os.makedirs(ASSETS, exist_ok=True)
    entries = {}

    # ---- layered hero bodies (headless). Same body renderer as the legacy
    # single-layer sets, but with headless=True so only torso/limbs/weapon
    # are drawn. The game composites a herohead:* atlas on top at runtime.
    for key, spec in H.HERO_SPECS.items():
        spec = dict(spec, headless=True)   # renderer draws body only
        im = build(lambda d, k, f, s=spec: H.draw_human(s, d, k, f))
        path = os.path.join(ASSETS, 'herobody_%s.png' % key)
        im.save(path, optimize=True)
        entries['herobody:' + key] = {'uri': data_uri(im), 'png': os.path.getsize(path)}
        print('herobody %-10s %s  %d KB' % (key, im.size, os.path.getsize(path) // 1024))

    for key in H.HERO_SPECS.items():
        pass

    # ---- standalone head atlases (one per head style) ----
    # NOTE: heads are keyed 'herohead:<style>'; the sex suffix on the PNG is
    # only for preview convenience (heads already encode male/female art).
    for key, spec in H.HEAD_SPECS.items():
        im = build(lambda d, k, f, s=spec: H.draw_head(s, d, k, f))
        path = os.path.join(ASSETS, 'herohead_%s.png' % key)
        im.save(path, optimize=True)
        entries['herohead:' + key] = {'uri': data_uri(im), 'png': os.path.getsize(path)}
        print('herohead %-10s %s  %d KB' % (key, im.size, os.path.getsize(path) // 1024))

    # ---- legacy single-layer atlases (kept so the live game keeps working
    #      until the layered renderer lands in index.html) ----
    for key, spec in H.HERO_SPECS.items():
        if key in ('thief_m', 'thief_f'):
            spec = A.HERO_ANIME_SPECS[key]
            im = build(lambda d, k, f, s=spec: T.draw_thief_hd(s, d, k, f))
        elif key in A.HERO_ANIME_SPECS:
            spec = A.HERO_ANIME_SPECS[key]
            im = build(lambda d, k, f, s=spec: A.draw_anime_hero(s, d, k, f))
        else:
            im = build(lambda d, k, f, s=spec: H.draw_human(s, d, k, f))
        path = os.path.join(ASSETS, 'hero_%s.png' % key)
        im.save(path, optimize=True)
        entries['hero:' + key] = {'uri': data_uri(im), 'png': os.path.getsize(path)}
        print('hero %-10s %s  %d KB' % (key, im.size, os.path.getsize(path) // 1024))

    for name, spec in M.MOB_SPECS.items():
        slug = name.lower().replace(' ', '_')
        im = build(lambda d, k, f, s=spec: M.draw_mob(s, d, k, f))
        path = os.path.join(ASSETS, 'mob_%s.png' % slug)
        im.save(path, optimize=True)
        entries['mob:' + name] = {'uri': data_uri(im), 'png': os.path.getsize(path)}
        print('mob  %-12s %s  %d KB' % (name, im.size, os.path.getsize(path) // 1024))

    js = os.path.join(ASSETS, 'sprites_data.js')
    with open(js, 'w') as f:
        f.write('// generated by tools/build_atlas.py - do not edit\n')
        f.write('window.SPRITE_ATLASES=%s;\n' % json.dumps({k: v['uri'] for k, v in entries.items()},
                                                           separators=(',', ':')))
    print('\nwrote %s (%d KB, %d atlases)' % (js, os.path.getsize(js) // 1024, len(entries)))


if __name__ == '__main__':
    main()