// Current catalog is evaluated through the existing DOM test harness; effects are never copied by hand.
// NODE_PATH=/path/to/jsdom-and-three/node_modules node tools/make_card_comparison.js
const fs=require('node:fs'),path=require('node:path');
const {createGame}=require('./tests/helpers/game');const g=createGame();
const source=JSON.parse(g.ev('JSON.stringify({build:BUILD,maps:MAPS.map(m=>m.n),cards:CARD_CATALOG})'));g.close();
const root=path.resolve(__dirname,'..'),proposals=JSON.parse(fs.readFileSync(path.join(root,'Updates/card-effect-proposal/proposals.json'),'utf8'));
const proposal=new Map(proposals.map(p=>[p.family,p]));
const label={str:'STR',agi:'AGI',dex:'DEX',luk:'LUK',int:'INT',vit:'VIT',hp:'Max HP',hpPct:'Max HP',atk:'ATK',matk:'Magic power',crit:'Crit chance',cdm:'Crit damage',aspd:'Attack speed',move:'Movement speed',field:'Normal-monster damage',def:'DEF',mdef:'MDEF',flee:'Flee'};
const percentage=new Set(['hpPct','atk','matk','crit','aspd','move','field']);
const effect=e=>e.k==='cdm'?`Crit damage +${(e.v/100).toFixed(2)}×`:`${label[e.k]||e.k} +${e.v}${percentage.has(e.k)?'%':''}`;
const rows=source.cards.filter(c=>!c.nightmare).map(c=>{const nm=source.cards.find(n=>n.family===c.family&&n.nightmare),family=c.family.replace(/ Card$/,''),p=proposal.get(family);if(!nm)throw Error('Missing Nightmare '+family);return {family,map:source.maps[c.map],boss:c.bossCard,fit:c.fit,changed:!!p,title:p?.title||'Keep current effect',before:c.effects.map(effect).join(' · '),beforeNM:nm.effects.map(effect).join(' · '),after:p?.normal||c.effects.map(effect).join(' · '),afterNM:p?.nightmare||nm.effects.map(effect).join(' · ')};});
if(source.cards.length!==180||rows.length!==90||rows.filter(r=>r.changed).length!==38||proposals.some(p=>!rows.some(r=>r.family===p.family)))throw Error('Card coverage mismatch');
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const render=r=>`<article class="card ${r.changed?'changed':'retained'}" data-map="${esc(r.map)}" data-changed="${r.changed}" data-search="${esc([r.family,r.title,r.before,r.after,r.beforeNM,r.afterNM].join(' ').toLowerCase())}"><header><div><small>${esc(r.map)}${r.boss?' · MVP':''}</small><h2>${esc(r.family)} Card</h2></div><span class="badge">${r.changed?'Proposed change':'Keep current'}</span></header><p class="fit">Slots: ${esc(r.fit.map(k=>({weapon:'Weapons',armor:'Armor',head:'Headgear',off:'Shields',leg:'Legwear',acc:'Accessories'})[k]||k).join(', '))} · same slots proposed for both forms</p><div class="comparison"><section><h3>Before · live</h3><b>Normal</b><p>${esc(r.before)}</p><b>Nightmare</b><p>${esc(r.beforeNM)}</p></section><section class="after"><h3>After · ${r.changed?'proposal':'unchanged'}</h3>${r.changed?`<h4>${esc(r.title)}</h4>`:''}<b>Normal</b><p>${esc(r.after)}</p><b>Nightmare</b><p>${esc(r.afterNM)}</p></section></div></article>`;
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Card effects — before & after</title><style>
:root{color-scheme:light;--ink:#24362e;--line:#cdd5c9;--green:#246149}*{box-sizing:border-box}body{margin:0;background:#f3f1e9;color:var(--ink);font:15px/1.55 system-ui,sans-serif}.wrap{max-width:1180px;margin:auto;padding:26px 20px}h1{font:700 clamp(26px,5vw,42px)/1.12 Georgia,serif;margin:10px 0}h2{font-size:20px;margin:3px 0}h3{margin:0 0 12px;text-transform:uppercase;letter-spacing:.08em;font-size:11px}h4{margin:0 0 10px;font-size:16px}p{margin:5px 0 16px}.eyebrow{color:var(--green);font-size:11px;letter-spacing:.15em;text-transform:uppercase;font-weight:700}.notice{background:#e2eade;border-left:4px solid #60815e;border-radius:5px;padding:14px 18px}.metrics{display:flex;gap:24px;flex-wrap:wrap;margin:18px 0}.metrics b{display:block;font-size:27px}.metrics span{font-size:12px}.controls{position:sticky;top:0;z-index:2;background:#f3f1e9f5;border-block:1px solid var(--line);display:flex;gap:12px;flex-wrap:wrap;padding:14px 0;margin:20px 0}.controls label{display:grid;font-size:11px;font-weight:700;gap:4px}.controls label:first-child{flex:1;min-width:150px}input,select,button{font:inherit;border:1px solid #a0b29f;border-radius:5px;padding:8px;background:#fff;color:var(--ink);max-width:100%}button{cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #d9b762;outline-offset:2px}#result{font-size:12px}.card{margin:16px 0;border:1px solid var(--line);border-radius:10px;background:#fffdf7;overflow:hidden}.card[hidden]{display:none}.card header{padding:18px 20px 0;display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}.card small{font-size:11px;color:#687767}.badge{font-size:11px;align-self:center;border:1px solid #a6b7a0;border-radius:20px;padding:4px 9px;color:#45633b}.changed .badge{color:#7b5521;background:#fff0c8;border-color:#d1b677}.fit{padding:0 20px;font-size:12px;color:#687767}.comparison{display:grid;grid-template-columns:1fr 1fr;border-top:1px solid var(--line)}.comparison section{padding:18px 20px}.comparison b{font-size:12px}.comparison p:last-child{margin-bottom:0}.after{background:#edf3e9;border-left:1px solid var(--line)}.retained .after{background:#f6f6f0}details{margin:15px 0;padding:12px;background:#e9ece3;border-radius:6px}summary{cursor:pointer;font-weight:650}footer{font-size:12px;color:#69776b;margin-top:30px}#empty{padding:25px;text-align:center}@media(max-width:600px){.wrap{padding:18px 12px}.controls{position:static}.comparison{grid-template-columns:1fr}.after{border-left:0;border-top:1px solid var(--line)}.card header{padding:15px 15px 0}.comparison section{padding:15px}.fit{padding:0 15px}.controls label{flex:1;min-width:130px}.metrics{gap:18px}}@media print{.controls,button{display:none}.card{break-inside:avoid}.wrap{padding:0}.comparison{grid-template-columns:1fr 1fr}}
</style></head><body><main class="wrap"><span class="eyebrow">Prontera Grind · card review</span><h1>Card effects, before &amp; after.</h1><p>Current Normal and Nightmare effects beside the suggested replacement. Search a card or compare one map at a time.</p><div class="notice"><b>Proposals only — no card effects have changed in the game.</b><br>“Before” comes from ${esc(source.build)}. The 38 revised families address repeated effects; 52 families keep their current effects. Slots and existing family/boss/socket limits stay the same in this proposal.</div><div class="metrics"><span><b>180</b>current card definitions</span><span><b>38</b>families proposed to change</span><span><b>52</b>families kept</span></div><details><summary>How to read the proposed values</summary><p>Nightmare keeps the proposed mechanic with 25% stronger positive numeric bonuses. Trigger counts, durations, cooldowns and penalties stay fixed. Peco Peco boosts attack speed against ordinary monsters; Zombie reduces their incoming damage without healing. Elder Willow boosts area magic without a movement condition. Ambernite adds flat MDEF (matching Wraith’s amount, as requested); its existing slots are retained. All equipment/card movement still shares the 20% cap. Conditional effects need implementation and balance testing before release.</p><p>Crit, attack-speed, movement and healing caps still apply. Triggered damage cannot trigger more card effects. Shields refresh instead of stacking. Scorpion supplies its own poison; it does not require an existing poison skill. Existing cards should use explicit conversion rather than silently changing equipped builds.</p><p>DEF/MDEF penetration affects only the stated hit. Healing/EXP/loot and pet bonuses need online/offline parity checks. Percentage drop bonuses multiply the base chance; they are not percentage points.</p></details><div class="controls"><label>Find a card or effect<input id="search" type="search" placeholder="Name, effect, role…"></label><label>Show<select id="show"><option value="changed">Proposed changes</option><option value="all">All 90 families</option><option value="retained">Kept effects</option></select></label><label>Map<select id="map"><option value="">All maps</option>${source.maps.map(m=>`<option>${esc(m)}</option>`).join('')}</select></label><button id="print" type="button">Print / save PDF</button></div><p id="result" role="status"></p><div id="cards">${rows.map(render).join('')}</div><p id="empty" hidden>No cards match these filters.</p><footer>Current effects are read from index.html. Proposed values are review targets, not tested balance outcomes. Pet bonding remains 1 / 3 / 6 / 10 / 15 duplicates. No quest redesign is included.</footer></main><script>
const cards=[...document.querySelectorAll('.card')],search=document.getElementById('search'),show=document.getElementById('show'),map=document.getElementById('map');function filter(){const q=search.value.trim().toLowerCase();let n=0;for(const c of cards){const yes=(!q||c.dataset.search.includes(q))&&(!map.value||c.dataset.map===map.value)&&(show.value==='all'||(show.value==='changed')===(c.dataset.changed==='true'));c.hidden=!yes;if(yes)n++;}document.getElementById('result').textContent=n+(n===1?' family · ':' families · ')+(n*2)+' Normal/Nightmare definitions';document.getElementById('empty').hidden=n>0;}search.addEventListener('input',filter);show.addEventListener('change',filter);map.addEventListener('change',filter);document.getElementById('print').onclick=()=>window.print();filter();
</script></body></html>`;
const dest=path.join(root,'Updates/cards-gear-audit/card-effect-comparison.html');fs.writeFileSync(dest,html);
const output=path.join(process.env.WORKSPACE_ROOT||path.resolve(root,'../../../..'),'output');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'card-effects-before-after.html'),html);
console.log('Wrote 90 families / 180 definitions; 38 proposed replacements.');
